### PR TITLE
Add link to RubyMotion Internationalization talk as well as 15-01-08 meetup notes

### PR DESCRIPTION
**Pull request by ramonh**

### CODE REVIEW

**Comment by beanieboi** [comment]
hey, thanks for the talk and the PR!
can you please embed the pdf in the PR, so we have a self containing repository.

**Comment by ramonh** [comment]
Hey there! Thanks for the feedback. I hope I've done it correctly.

**Comment by beanieboi** [comment]
perfect, thanks! :) :confetti_ball: :tada:

**Comment by ramonh** [comment]
Cool, thank you!

**Comment by alicetragedy** [comment]
sorry @beanieboi, my bad - told @ramonh that (just) the direct link was ok for now, since the repo is still a bit of a mess. :)

**Comment by beanieboi** [comment]
no worries! if we get the pdf we are more flexible. but linking to the speaker is a nice attribution to the speaker. so i'm also not sure whats "the best" (tm) way to do it

**Pull request merged**
